// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type CrawlerLog struct {
	ID            string
	DataSourceID  string
	UrlFrontierID pgtype.Text
	JobsID        pgtype.Text
	EventType     string
	Message       pgtype.Text
	// Stores structured log data including context, parameters, and results
	Details   []byte
	CreatedAt time.Time
}

type DataSource struct {
	ID          string
	Name        string
	Country     string
	SourceType  string
	BaseUrl     pgtype.Text
	Description pgtype.Text
	Config      []byte
	IsActive    bool
	CreatedAt   time.Time
	UpdatedAt   time.Time
	DeletedAt   pgtype.Timestamptz
}

type Extraction struct {
	ID             string
	UrlFrontierID  string
	SiteContent    pgtype.Text
	ArtifactLink   pgtype.Text
	RawPageLink    pgtype.Text
	ExtractionDate time.Time
	ContentType    pgtype.Text
	// Stores structured data extracted from the source
	Metadata  []byte
	Language  string
	PageHash  pgtype.Text
	Version   int32
	CreatedAt time.Time
	UpdatedAt time.Time
}

type ExtractionVersion struct {
	ID           string
	ExtractionID string
	SiteContent  pgtype.Text
	ArtifactLink pgtype.Text
	RawPageLink  pgtype.Text
	// Stores structured data extracted from the source at this version
	Metadata  []byte
	PageHash  pgtype.Text
	Version   int32
	CreatedAt time.Time
}

type Job struct {
	ID         string
	Status     string
	CreatedAt  time.Time
	UpdatedAt  time.Time
	StartedAt  pgtype.Timestamptz
	FinishedAt pgtype.Timestamptz
}

type UrlFrontier struct {
	ID           string
	DataSourceID string
	Domain       string
	Url          string
	Keyword      pgtype.Text
	Priority     int16
	// 0: Pending, 1: Crawled, 2: Changed, 3: Failed, 4: Scheduled, 5: Processing
	Status        int16
	Attempts      int16
	LastCrawledAt pgtype.Timestamptz
	NextCrawlAt   pgtype.Timestamptz
	ErrorMessage  pgtype.Text
	// Stores search parameters and context information
	Metadata  []byte
	CreatedAt time.Time
	UpdatedAt time.Time
}
